name: Github Pages
on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: client

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js 16 LTS

      - name: Set Node Options (Fix for OpenSSL Issue)
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install Packages
        run: npm install

      - name: Build page
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}

      - name: 404 page
        run: cp ./build/index.html ./build/404.html
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: client/build 
          CLEAN: true 
 
